### PR TITLE
Add the ability to drop whole classes

### PR DESCRIPTION
**Pull request by dankrause**
implments #100

### CODE REVIEW

**Comment by dankrause** [comment]
If there's a better place to put this, let me know, and I'll update the PR.

This should allow us to clean up after our unit tests, if we want.

**Comment by dgrtwo** [comment]
Why not from the object itself; i.e.

    GameScore.drop()

**Comment by dankrause** [comment]
That is essentially what I'm doing here.

```python
class GameScore(ParseBase):
    pass

GameScore.drop_class() # completely removes the GameScore class from your app
```

**Comment by dankrause** [comment]
Odd, it doesn't seem to work when subclassing from Object. Only when subclassing from ParseBase (which Object is a subclass of...)

Any ideas?

**Comment by dankrause** [comment]
It should work when subclassed from Object now. I've also renamed the method to just "drop", rather than "drop_class".

**Comment by dankrause** [comment]
Or were you suggesting that I add the method to Object rather than ParseBase?

**Pull request merged**
